### ISSUE TITLE
google test disappear after linking with metrics.lib

### ISSUE THREAD

**Issue by phoenicyan** [DarkWanderer/metrics-cpp#47]
I noticed that as soon as I link metrics.lib to my VS2022 project and call createRegistry(),  the Test Explorer no longer shows any Google Tests. Is this because of a conflict with Catch2? How to resolve this?

**Comment by DarkWanderer** [comment]
Hi,

Yes, it is likely because of conflict between test libraries. Do you use `add_eubdirectory` to add this library? Can you try with EXCLUDE_FROM_ALL flag?

**Comment by phoenicyan** [comment]
Hi! Thank you for quick response! I'm not sure how to use EXCLUDE_FROM_ALL flag after I generated VS2022 project. Instead I copied header and src files directly into my project, and after a few trivial changes, it all worked. This issue can be closed as resolved. Thanks for the handy tool!

**Comment by phoenicyan** [comment]
found workaround
